version: 2

models:
  - name: dim_category
    description: "Dimension table for categories of transactions"
    constraints:
      - type: primary_key
        columns: [category_id]
    columns:
      - name: category_id
        description: "Unique identifier for the category"
        data_type: integer
      - name: category
        description: "Name of the category"
        data_type: string
      - name: category_pt
        description: "Name of the category in Portuguese"
        data_type: string
      - name: upper_category
        description: "Upper level category"
        data_type: string
      - name: upper_category_pt
        description: "Upper level category in Portuguese"
        data_type: string
      - name: inserted_at
        description: "Timestamp when the record was inserted"
        data_type: datetime
      - name: updated_at
        description: "Timestamp when the record was last updated"
        data_type: datetime

  - name: dim_coin
    description: "Dimension table for coins"
    constraints:
      - type: primary_key
        columns: [coin_id]
    columns:
      - name: coin_id
        description: "Unique identifier for the coin"
        data_type: integer
      - name: coin_code
        description: "Code of the coin"
        data_type: string
      - name: coin_name
        description: "Name of the coin"
        data_type: string
      - name: coin_symbol
        description: "Symbol of the coin"
        data_type: string
      - name: coin_type
        description: "Type of the coin"
        data_type: string
      - name: thousands_separator
        description: "Thousands separator used for the coin"
        data_type: string
      - name: decimal_separator
        description: "Decimal separator used for the coin"
        data_type: string
      - name: inserted_at
        description: "Timestamp when the record was inserted"
        data_type: datetime
      - name: updated_at
        description: "Timestamp when the record was last updated"
        data_type: datetime

  - name: dim_date
    description: "Dimension table for dates"
    constraints:
      - type: primary_key
        columns: [date_full]
    columns:
      - name: date_full
        description: "Full date"
        data_type: date
      - name: year
        description: "Year"
        data_type: integer
      - name: year_quarter
        description: "Quarter of the year"
        data_type: string
      - name: month
        description: "Month"
        data_type: string
      - name: month_number
        description: "Month number"
        data_type: integer
      - name: week_number
        description: "Week number"
        data_type: integer
      - name: day
        description: "Day of the month"
        data_type: integer
      - name: day_name_en
        description: "Day name in English"
        data_type: string
      - name: day_name_pt
        description: "Day name in Portuguese"
        data_type: string
      - name: is_weekend
        description: "Indicates if the day is a weekend"
        data_type: boolean

  - name: dim_description
    description: "Dimension table for descriptions"
    constraints:
      - type: primary_key
        columns: [description_id]
    columns:
      - name: description_id
        description: "Unique identifier for the description"
        data_type: integer
      - name: description
        description: "Description text"
        data_type: string
      - name: inserted_at
        description: "Timestamp when the record was inserted"
        data_type: datetime
      - name: updated_at
        description: "Timestamp when the record was last updated"
        data_type: datetime

  - name: dim_place
    description: "Dimension table for places"
    constraints:
      - type: primary_key
        columns: [place_id]
    columns:
      - name: place_id
        description: "Unique identifier for the place"
        data_type: integer
      - name: place
        description: "Name of the place"
        data_type: string
      - name: is_online
        description: "Indicates if the place is online"
        data_type: string
      - name: category_id
        description: "Category identifier"
        data_type: integer
      - name: inserted_at
        description: "Timestamp when the record was inserted"
        data_type: datetime
      - name: updated_at
        description: "Timestamp when the record was last updated"
        data_type: datetime

  - name: dim_source
    description: "Dimension table for sources"
    constraints:
      - type: primary_key
        columns: [source_id]
    columns:
      - name: source_id
        description: "Unique identifier for the source"
        data_type: integer
      - name: bank_name
        description: "Name of the bank"
        data_type: string
      - name: source_type
        description: "Type of the source"
        data_type: string
      - name: source_account
        description: "Source account"
        data_type: string
      - name: source_start
        description: "Start date of the source"
        data_type: date
      - name: source_end
        description: "End date of the source"
        data_type: date
      - name: bill_date
        description: "Bill date"
        data_type: date
      - name: bill_amount
        description: "Bill amount"
        data_type: decimal

  - name: dim_transaction_type
    description: "Dimension table for transaction types"
    constraints:
      - type: primary_key
        columns: [type_id]
    columns:
      - name: type_id
        description: "Unique identifier for the transaction type"
        data_type: integer
      - name: type_description
        description: "Description of the transaction type"
        data_type: string
      - name: type_description_pt
        description: "Description of the transaction type in Portuguese"
        data_type: string
      - name: inserted_at
        description: "Timestamp when the record was inserted"
        data_type: datetime
      - name: updated_at
        description: "Timestamp when the record was last updated"
        data_type: datetime

  - name: fact_transactions
    description: "Fact table for transactions"
    constraints:
      - type: primary_key
        columns: [transaction_id]
    columns:
      - name: transaction_id
        description: "Unique identifier for the transaction"
        data_type: integer
      - name: transaction_date
        description: "Date of the transaction"
        data_type: date
      - name: source_id
        description: "Identifier for the source"
        data_type: integer
      - name: description_id
        description: "Identifier for the description"
        data_type: integer
      - name: place_id
        description: "Identifier for the place"
        data_type: integer
      - name: type_id
        description: "Identifier for the transaction type"
        data_type: integer
      - name: category_id
        description: "Identifier for the category"
        data_type: integer
      - name: coin_id
        description: "Identifier for the coin"
        data_type: integer
      - name: amount
        description: "Amount of the transaction"
        data_type: decimal
      - name: income_or_expense
        description: "Indicates if the transaction is an income or expense"
        data_type: string
      - name: amount_abs
        description: "Absolute amount of the transaction"
        data_type: decimal
      - name: daily_cumulative_balance
        description: "Cumulative balance for the day"
        data_type: decimal

  - name: gold_places_rank
    description: "Rank of places based on expenditure"
    columns:
      - name: rank
        description: "Rank of the place"
        data_type: integer
      - name: place
        description: "Name of the place"
        data_type: string
      - name: num_transactions
        description: "Number of transactions"
        data_type: integer
      - name: sum_transactions
        description: "Sum of transactions"
        data_type: decimal
