version: 2

sources:
  - name: bronze # this is the source_name
    schema: expenses_tracker_bronze

    tables:
      - name: bills__inter
      - name: bills__nubank
      - name: statements__nubank
      - name: statements__inter
      - name: bills_nubank_regex_mapping
      - name: places
      - name: transaction_types
      - name: categories
      - name: coins
      - name: bills_inter_regex_mapping
      - name: statements_nubank_regex_mapping
      - name: statements_inter_regex_mapping